version: "2.2"
services:
############################################# NGINX #############################################
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: 'elk-nginx'
    restart: unless-stopped
    ports:
      - 8000:80
      - 8443:443
    networks:
      - default
    cpus: 2
    mem_limit: 150M

############################################# Logstash #############################################
  logstash:
    build:
      context: .
      dockerfile: docker/Dockerfile-logstash
    container_name: 'elk-logstash'
    restart: unless-stopped
    ports:
      - 5044:5044
    networks:
      - default
    cpus: 2
    mem_limit: 1G

############################################# Kibana #############################################
  kibana:
    build:
      context: .
      dockerfile: docker/Dockerfile-kibana
    container_name: 'elk-kibana'
    restart: unless-stopped
    ports:
      - 5601:5601
    networks:
      - default
    cpus: 2
    mem_limit: 1G

############################################# Elasticsearch #############################################
  elasticsearch:
    build:
      context: .
      dockerfile: docker/Dockerfile-elasticsearch
    container_name: 'elk-elasticsearch'
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
        - es-data:/usr/share/elasticsearch/data
    networks:
      - default
    cpus: 2
    mem_limit: 1G

volumes:
  es-data:

networks:
  default:
