FROM docker.elastic.co/logstash/logstash:7.13.4

# Copy SSL
COPY conf/ssl/logstash.crt /usr/share/logstash/ssl/logstash.crt
COPY conf/ssl/logstash.key /usr/share/logstash/ssl/logstash.key

# Copy logstash.yml
RUN rm -rf /usr/share/logstash/pipeline/logstash.conf
COPY conf/logstash/logstash.yml /usr/share/logstash/config/logstash.yml

# Copy pipeline configs
COPY conf/logstash/pipeline/ /usr/share/logstash/pipeline
