FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
COPY conf/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Copy SSL
COPY conf/ssl/docker.crt /usr/share/elasticsearch/ssl/elasticsearch.crt
COPY conf/ssl/docker.key /usr/share/elasticsearch/ssl/elasticsearch.key

# Expose HTTP and transport port
EXPOSE 9200 9300
